language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
  - "3.6"
install:
  # ensure that we have the full tag information available for version.py
  #--unshallow --tags
  - git fetch
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --remove channels defaults && conda config --add channels conda-forge
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # install dependencies
  #- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy nose pip matplotlib coverage
  - conda install numpy scipy nose pip matplotlib coverage astropy six coveralls coverage pycodestyle pip
  - conda install -y 'libgfortran =3.0.0'
  - pip install coveralls
  - pip install git+https://github.com/HERA-Team/pyuvdata.git
  - conda list

script:
  - python setup.py build_ext --force --inplace
  - nosetests simpleDS --nologcapture --with-coverage --cover-package=simpleDS
  - pycodestyle --ignore=E501,W503 simpleDS

after_success:
  - coveralls
